# Generated by Django 3.2.7 on 2022-02-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='desc',
            field=models.CharField(default='asc', max_length=50, verbose_name='Описание2'),
        ),
    ]
