# Generated by Django 3.2.7 on 2022-02-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_radio_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='name',
            field=models.CharField(default='aschsaj', max_length=60, verbose_name='sadf'),
        ),
        migrations.AddField(
            model_name='radio',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=2),
        ),
    ]
