# Generated by Django 3.2.7 on 2022-02-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220209_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radio',
            old_name='GENDER',
            new_name='gender',
        ),
    ]
