# Generated by Django 3.2.7 on 2022-02-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_gender_radio_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='options',
            field=models.BooleanField(default=False, verbose_name='Кассир'),
        ),
        migrations.AlterField(
            model_name='radio',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2),
        ),
    ]
