# Generated by Django 3.2.7 on 2022-02-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220208_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radio',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='name',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='shirt_size',
        ),
        migrations.AddField(
            model_name='radio',
            name='GENDER',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='S', max_length=2),
        ),
    ]
